name: 'Get Shopify Theme ID'
description: 'Extract theme ID by its name using Shopify REST Admin API'
inputs:
  store:
    description: 'Shopify Store URL'
    required: true
  token:
    description: 'Shopify API Access Token'
    required: true
  theme_name:
    description: 'Theme name'
    required: true
outputs:
  theme_id:
    description: 'ID of the Theme'
runs:
  using: 'node16'
  main: 'dist/index.js'
